server:
  port: 9011
#dubbo:
#  application:
#    name: provider
#  server: true
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  protocol:
#    name: dubbo
#    port: 20880
spring:
#  dubbo:
#    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
#      name: consumer
#    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
#      address: zookeeper://127.0.0.1:2181
#    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。
#      name: dubbo
#      port: 20880
#    consumer:
#      check: false
#    reference:
#      loadbalance: roundrobin #轮询机制
      #loadbalance: random #随机机制
      #loadbalance: leastactive #最少活跃调用数机制
  redis:
    host: 192.168.126.133
    port: 6379
    timeout: 30s
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      name: user
      url: jdbc:mysql://192.168.126.133:3306/user?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  data:
    elasticsearch:
      cluster-nodes: 192.168.126.133:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.tigrex.geo.entity
  check-config-location: false