server:
  port: 9001
spring:
  redis:
    host: 47.99.243.32
    port: 6379
    timeout: 30s
    password: 123456
    jedis:
      pool:
        max-active: 3
        max-idle: 3
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.99.243.32:3306/tigrex?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: tigrex
      password: 123456
  kafka:
    bootstrap-servers: 47.99.243.32:9092
